Thu Aug 4 01:54:40 IDT 2022

SLURM_JOBID:		 4175364
SLURM_JOB_NODELIST:	 cs-cpu-21 


Traceback (most recent call last):
  File "batch_one_sqlite_2_csv.py", line 139, in <module>
    map_data()
  File "batch_one_sqlite_2_csv.py", line 94, in map_data
    meta_df = pd.read_csv("metadata.csv")
  File "/storage/modules/packages/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/storage/modules/packages/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/storage/modules/packages/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/modules/packages/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/storage/modules/packages/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/storage/modules/packages/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/storage/modules/packages/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/storage/modules/packages/anaconda3/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'metadata.csv'
